// <auto-generated />
namespace Gama.Musicas.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmailAlbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailAlbum));
        
        string IMigrationMetadata.Id
        {
            get { return "201609262329220_EmailAlbum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
